# Generated by Django 5.2 on 2025-04-29 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('edition_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paper_size', models.CharField(max_length=100)),
                ('plate_size', models.CharField(max_length=100)),
                ('technique', models.CharField(choices=[('sp', 'Screenprint'), ('mt', 'Monotype'), ('li', 'Lithography'), ('co', 'Collagraph'), ('dp', 'Drypoint'), ('at', 'Aquatint'), ('mt', 'Mezzotint'), ('et', 'Etching'), ('eg', 'Engraving'), ('pg', 'Photogravure'), ('lc', 'Linocut'), ('wc', 'Woodcut'), ('mk', 'Mokuhanga'), ('cb', 'Carborundum')], default=0)),
                ('margin_upper', models.CharField(max_length=100)),
                ('margin_lower', models.CharField(max_length=100)),
                ('margin_sides', models.CharField(max_length=100)),
                ('available_prints', models.CharField(max_length=50)),
                ('status', models.CharField(choices=0)),
                ('edition_type', models.CharField(choices=0)),
            ],
        ),
    ]
