# Generated by Django 5.2 on 2025-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_edition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='edition_type',
            field=models.CharField(choices=[('lmt', 'Limited'), ('op', 'Open'), ('va', 'Varied')], default='lmt'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('ip', 'In Progress'), ('c', 'Complete'), ('a', 'Archive')], default='ip'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='technique',
            field=models.CharField(choices=[('sp', 'Screenprint'), ('mt', 'Monotype'), ('li', 'Lithography'), ('co', 'Collagraph'), ('dp', 'Drypoint'), ('at', 'Aquatint'), ('mt', 'Mezzotint'), ('et', 'Etching'), ('eg', 'Engraving'), ('pg', 'Photogravure'), ('lc', 'Linocut'), ('wc', 'Woodcut'), ('mk', 'Mokuhanga'), ('cb', 'Carborundum')], default='sp'),
        ),
    ]
