# Generated by Django 5.2 on 2025-04-29 20:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_edition_edition_type_alter_edition_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edition_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
