# Generated by Django 5.2 on 2025-04-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_edition_edition_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='edition_image',
            new_name='image',
        ),
    ]
