# Generated by Django 5.2 on 2025-04-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_edition_image_edition_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField()),
                ('notes', models.TextField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.edition')),
            ],
        ),
    ]
