# Generated by Django 5.2 on 2025-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink_name', models.CharField(max_length=200)),
                ('ink_color', models.CharField(max_length=100)),
                ('ink_type', models.CharField(choices=[('ri', 'Relief/Block Ink'), ('si', 'Screen Printing Ink'), ('ei', 'Etching/Intaglio Ink'), ('li', 'Lithography Ink'), ('mi', 'Monotype Ink')], default='ri')),
                ('ink_based', models.CharField(choices=[('ob', 'Oil Based'), ('wb', 'Water Based')], default='ob')),
                ('ink_qty', models.PositiveIntegerField()),
            ],
        ),
    ]
