# Generated by Django 5.2 on 2025-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_ink'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='ink',
            field=models.ManyToManyField(to='main_app.ink'),
        ),
    ]
