# Generated by Django 5.2 on 2025-04-30 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_ink_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=200)),
                ('paper_color', models.CharField(max_length=100)),
                ('paper_size', models.CharField(max_length=100)),
                ('paper_weight', models.CharField(max_length=100)),
                ('paper_qty', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='paper',
            field=models.ManyToManyField(to='main_app.paper'),
        ),
    ]
