# Generated by Django 5.2 on 2025-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_paper_edition_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='edition_type',
            field=models.CharField(choices=[('lmt', 'Limited'), ('op', 'Open'), ('va', 'Varied')], default='lmt', max_length=200),
        ),
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('ip', 'In Progress'), ('c', 'Complete'), ('a', 'Archive')], default='ip', max_length=200),
        ),
        migrations.AlterField(
            model_name='edition',
            name='technique',
            field=models.CharField(choices=[('sp', 'Screenprint'), ('mt', 'Monotype'), ('li', 'Lithography'), ('co', 'Collagraph'), ('dp', 'Drypoint'), ('at', 'Aquatint'), ('mt', 'Mezzotint'), ('et', 'Etching'), ('eg', 'Engraving'), ('pg', 'Photogravure'), ('lc', 'Linocut'), ('wc', 'Woodcut'), ('mk', 'Mokuhanga'), ('cb', 'Carborundum')], default='sp', max_length=200),
        ),
        migrations.AlterField(
            model_name='ink',
            name='ink_based',
            field=models.CharField(choices=[('ob', 'Oil Based'), ('wb', 'Water Based')], default='ob', max_length=200),
        ),
        migrations.AlterField(
            model_name='ink',
            name='ink_type',
            field=models.CharField(choices=[('ri', 'Relief/Block Ink'), ('si', 'Screen Printing Ink'), ('ei', 'Etching/Intaglio Ink'), ('li', 'Lithography Ink'), ('mi', 'Monotype Ink')], default='ri', max_length=200),
        ),
    ]
